export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAIL = 'GET_PROJECT_LIST_FAIL';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';

export const GET_MARKER_LIST_SUCCESS = 'GET_MARKER_LIST_SUCCESS';
export const GET_MARKER_LIST_FAIL = 'GET_MARKER_LIST_FAIL';
export const GET_CURRENT_MARKER_LIST_SUCCESS =
  'GET_CURRENT_MARKER_LIST_SUCCESS';
export const GET_CURRENT_MARKER_LIST_FAIL = 'GET_CURRENT_MARKER_LIST_FAIL';
export const ADD_CURRENT_MARKER_SUCCESS = 'ADD_CURRENT_MARKER_SUCCESS';
export const ADD_CURRENT_MARKER_FAIL = 'ADD_CURRENT_MARKER_FAIL';
export const DELETE_CURRENT_MARKER_SUCCESS = 'DELETE_CURRENT_MARKER_SUCCESS';
export const DELETE_CURRENT_MARKER_FAIL = 'DELETE_CURRENT_MARKER_FAIL';
export const UPDATE_MARKER_SUCCESS = 'UPDATE_MARKER_SUCCESS';
export const UPDATE_MARKER_FAIL = 'UPDATE_MARKER_FAIL';

export const GET_CRITERIA_LIST_SUCCESS = 'GET_CRITERIA_LIST_SUCCESS';
export const GET_CRITERIA_LIST_FAIL = 'GET_CRITERIA_LIST_FAIL';
export const UPDATE_CRITERIA_SUCCESS = 'UPDATE_CRITERIA_SUCCESS';
export const UPDATE_CRITERIA_FAIL = 'UPDATE_CRITERIA_FAIL';
export const DELETE_CRITERIA_SUCCESS = 'DELETE_CRITERIA_SUCCESS';
export const DELETE_CRITERIA_FAIL = 'DELETE_CRITERIA_FAIL';
export const CREATE_CRITERIA_SUCCESS = 'CREATE_CRITERIA_SUCCESS';
export const CREATE_CRITERIA_FAIL = 'CREATE_CRITERIA_FAIL';

export const GET_STUDENT_LIST_SUCCESS = 'GET_STUDENT_LIST_SUCCESS';
export const GET_STUDENT_LIST_FAIL = 'GET_STUDENT_LIST_FAIL';
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';
export const DELETE_STUDENT_FAIL = 'DELETE_STUDENT_FAIL';
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL';
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS';
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL';
export const IMPORT_STUDENTS_SUCCESS = 'IMPORT_STUDENTS_SUCCESS';
export const IMPORT_STUDENTS_FAIL = 'IMPORT_STUDENTS_FAIL';

export const DELETE_GROUP_SUCCESS = 'DELETE_GROUP_SUCCESS';
export const DELETE_GROUP_FAIL = 'DELETE_GROUP_FAIL';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const CREATE_GROUP_FAIL = 'CREATE_GROUP_FAIL';
export const GET_MEMEBR_LIST_SUCCESS = 'GET_MEMEBR_LIST_SUCCESS';
export const GET_MEMEBR_LIST_FAIL = 'GET_MEMEBR_LIST_FAIL';
export const GET_CURRENT_MEMEBR_LIST_SUCCESS =
  'GET_CURRENT_MEMEBR_LIST_SUCCESS';
export const GET_CURRENT_MEMEBR_LIST_FAIL = 'GET_CURRENT_MEMEBR_LIST_FAIL';
export const ADD_CURRENT_MEMEBR_SUCCESS = 'ADD_CURRENT_MEMEBR_SUCCESS';
export const ADD_CURRENT_MEMEBR_FAIL = 'ADD_CURRENT_MEMEBR_FAIL';
export const DELETE_CURRENT_MEMEBR_SUCCESS = 'DELETE_CURRENT_MEMEBR_SUCCESS';
export const DELETE_CURRENT_MEMEBR_FAIL = 'DELETE_CURRENT_MEMEBR_FAIL';

export const GET_SINGLE_RESULT_SUCCESS = 'GET_SINGLE_RESULT_SUCCESS';
export const GET_SINGLE_RESULT_FAIL = 'GET_SINGLE_RESULT_FAIL';
export const GET_ALL_RESULT_SUCCESS =
  'GET_ALL_RESULT_SUCCESS';
export const GET_ALL_RESULT_FAIL = 'GET_ALL_RESULT_FAIL';
export const UPDATE_RESULT_SUCCESS = 'UPDATE_RESULT_SUCCESS';
export const UPDATE_RESULT_FAIL = 'UPDATE_RESULT_FAIL';
