export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS';
export const GET_PROJECT_LIST_FAIL = 'GET_PROJECT_LIST_FAIL';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const CREATE_PROJECT_SUCCESS = 'CREATE_PROJECT_SUCCESS';
export const CREATE_PROJECT_FAIL = 'CREATE_PROJECT_FAIL';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAIL = 'UPDATE_PROJECT_FAIL';


export const GET_MARKER_LIST_SUCCESS = 'GET_MARKER_LIST_SUCCESS';
export const GET_MARKER_LIST_FAIL = 'GET_MARKER_LIST_FAIL';
export const UPDATE_MARKER_SUCCESS = 'UPDATE_MARKER_SUCCESS';
export const UPDATE_MARKER_FAIL = 'UPDATE_MARKER_FAIL';


export const GET_CRITERIA_LIST_SUCCESS = 'GET_CRITERIA_LIST_SUCCESS';
export const GET_CRITERIA_LIST_FAIL = 'GET_CRITERIA_LIST_FAIL';
export const UPDATE_CRITERIA_SUCCESS = 'UPDATE_CRITERIA_SUCCESS';
export const UPDATE_CRITERIA_FAIL = 'UPDATE_CRITERIA_FAIL';
export const DELETE_CRITERIA_SUCCESS = 'DELETE_CRITERIA_SUCCESS';
export const DELETE_CRITERIA_FAIL = 'DELETE_CRITERIA_FAIL';
export const CREATE_CRITERIA_SUCCESS = 'CREATE_CRITERIA_SUCCESS';
export const CREATE_CRITERIA_FAIL = 'CREATE_CRITERIA_FAIL';
